Sprint 2 review
AlexanderVasiliev23/yp-url-shortener pull request #11
Opened 2023-11-26 17:06 UTC by AlexanderVasiliev23

2023-11-28 14:39 UTC, maxlyaptsev requested changes

2023-11-28 14:39 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	application := app.New(conf, sugaredLogger)
не очень удобно прокидывать везде логер. Этот тот крайний случай где обычно его делают глобальной переменной

Т.е. можно сделать пакет logger,  глобальную переменную и метод Run/Init/Start который ее заполнит

2023-11-28 14:39 UTC, maxlyaptsev commented on internal/app/middlewares/logger/logger.go
> +package logger
nit: можно не делить на подпакеты, а сложить все файлы в middlewares - там не будет много файлов, 2-5 мидвары это нормально, больше особо и не бывает

2023-11-28 14:39 UTC, maxlyaptsev commented on internal/app/router.go
> +	e.Use(logger.Middleware(a.logger))
```suggestion
	e.Use(logger.Middleware(a.logger), gzip.Middleware())
```
их вроде можно через запятую перечислить

2023-11-28 14:39 UTC, maxlyaptsev commented on internal/app/storage/storageerrors/storage_errors.go
> +	ErrURLNotFound = errors.New("url is not found")
как отдельный пакет наверное нет смысла делать, даже если переиспользуется - ErrURLNotFound одного стореджа != ErrURLNotFound другого стореджа т.к. такие ошибки отличить будет сложно. Лучше скопипастить

2023-11-28 14:39 UTC, maxlyaptsev commented on internal/app/app.go
> +	_storage, err := storage.New(conf.StorageFilePath)
Написал в чатике подробнее. Тут нужно сделать дамп в файл независимым, а при обычной работе приложения писать все в память, периодически сбрасывая данные в файл. Использование файла замедляет приложение и нужно только для того чтобы не потерять данные

2023-11-29 11:27 UTC, AlexanderVasiliev23 commented on internal/app/router.go
> +	e.Use(logger.Middleware(a.logger))
Для наглядности хотел бы так оставить. Особенно будет актуально, когда будет больше мидлвар.

2023-11-29 11:28 UTC, AlexanderVasiliev23 commented on internal/app/middlewares/logger/logger.go
> +package logger
Понял. Хотел бы оставить как есть, т.к. у мидлвар могут быть еще вспомогательные приватные функции и, чтобы не захламлять пакет, решил их разбить на несколько под каждую мидлварь.

2023-11-29 11:28 UTC, AlexanderVasiliev23 commented on cmd/shortener/main.go
> +	application := app.New(conf, sugaredLogger)
Сделал логер глобальной переменной

2023-11-29 17:48 UTC, maxlyaptsev commented on internal/app/router.go
> +	e.Use(logger.Middleware(a.logger))
их можно в каждой строке отдельно писать - тут вопрос форматирования, зато все мидлвары в одном скоупе и не потеряются

2023-11-29 17:51 UTC, maxlyaptsev commented on internal/app/storage/filestoragedecorator/filestoragedecorator.go
> +package filestoragedecorator
Лучше назвать функционально - dumper или workers/dump.go - в go в целом не принято использодвать ооп- патерны и их названия довольно чужеродные

2023-11-29 17:52 UTC, maxlyaptsev approved these changes

2023-11-29 17:59 UTC, merged