Sprint 4 review
AlexanderVasiliev23/yp-url-shortener pull request #19
Opened 2023-12-25 19:46 UTC by AlexanderVasiliev23

2023-12-26 16:34 UTC, maxlyaptsev requested changes

2023-12-26 16:34 UTC, maxlyaptsev commented on internal/app/handlers/user/urls/deleteurl/deleteurl.go
> +func Delete(linksStorage linksStorage, userContextFetcher userContextFetcher, deleteByTokenCh chan<- deleter.DeleteTask) echo.HandlerFunc {
Вообще в идеале если ручки будут реализовывать интерфейс HandlerFunc
С echo это сложней т.к. используется свой контекст. Но все зависимости можно вынести в конструктор

Второе - сырой канал не очень хорошо передавать в аргументы. Можно сделать метод-обертку в сервисе удаления

2023-12-26 16:34 UTC, maxlyaptsev commented on internal/app/handlers/shorten/batch/shorten_test.go
> +	h := Shorten(mockBatchSaver, tokenGeneratorMock, google.UUIDGenerator{}, &mock.UserContextFetcherMock{}, addr)
появился новый функционал, а тестов больше не стало. Ручки нужно тестировать на все возможные коды ответов - появилась возможность отдать 500 если не прошли авторизацию. Убедиться что это работает сейчас невозможно

2023-12-26 16:34 UTC, maxlyaptsev commented on internal/app/handlers/user/urls/deleteurl/deleteurl_test.go
> +	ch := make(chan<- deleter.DeleteTask, 1)
не вижу проверки что в канал что-то записалось. Этот тест проверяет только что ручка существует, но не проверяет что она работает

2023-12-26 16:34 UTC, maxlyaptsev commented on internal/app/workers/deleter/deleter.go
> +	ctx, cancelFn := context.WithTimeout(context.Background(), 30*time.Second)
```suggestion
	ctx, cancelFn := context.WithTimeout(context.Background(), w.maxExecutionTime)
```
лучше выносить в конфигурацию, так сложно увидеть, а параметр важный

2023-12-26 16:34 UTC, maxlyaptsev commented on internal/app/workers/deleter/deleter.go
> +				batch = batch[:0]
код нетривиальный и есть вероятность ошибиться и уйти в бесконечный цикл или обрезать данные. Тут нужен хороший unit тест

Можно потренироваться и сделать тест на производительность - bench тест

2023-12-26 17:13 UTC, AlexanderVasiliev23 commented on internal/app/handlers/get/get.go
> +		if shortLink.DeletedAt != nil {
Это чтобы возвращать код ответа 410 Gone для записи с DeletedAt != nil. В противном случае возвращать BadRequest. То есть как я понял, это два разных кейса: когда записи вообще нет или когда она есть, но была удалена (проставлен deletedAt)

2024-01-07 13:14 UTC, AlexanderVasiliev23 commented on internal/app/handlers/shorten/batch/shorten.go
> +func Shorten(saver batchSaver, tokenGenerator tokenGenerator, uuidGenerator uuidGenerator, userContextFetcher userContextFetcher, addr string) echo.HandlerFunc {
Поправил

2024-01-07 13:15 UTC, AlexanderVasiliev23 commented on internal/app/handlers/shorten/batch/shorten.go
> +		}
Хотел бы отбудить на 1:1, не совсем понял.

2024-01-07 13:15 UTC, AlexanderVasiliev23 commented on internal/app/handlers/user/urls/deleteurl/deleteurl.go
> +func Delete(linksStorage linksStorage, userContextFetcher userContextFetcher, deleteByTokenCh chan<- deleter.DeleteTask) echo.HandlerFunc {
По первому пунтку поправил.
По второму - хотел бы отбудить на 1:1, не совсем понял.

2024-01-07 13:15 UTC, AlexanderVasiliev23 commented on internal/app/handlers/shorten/batch/shorten_test.go
> +	h := Shorten(mockBatchSaver, tokenGeneratorMock, google.UUIDGenerator{}, &mock.UserContextFetcherMock{}, addr)
Добавил тесты

2024-01-07 13:15 UTC, AlexanderVasiliev23 commented on internal/app/handlers/user/urls/deleteurl/deleteurl_test.go
> +	ch := make(chan<- deleter.DeleteTask, 1)
Добавил проверку записи в канал

2024-01-07 13:16 UTC, AlexanderVasiliev23 commented on internal/app/workers/deleter/deleter.go
> +	ctx, cancelFn := context.WithTimeout(context.Background(), 30*time.Second)
Вынес в конфиг

2024-01-07 13:17 UTC, AlexanderVasiliev23 commented on internal/app/workers/deleter/deleter.go
> +				batch = batch[:0]
Написал тесты для разных случаев (кстати, пока писал тест, понял, что не все учел, тест помог).
По поводу benchmark тестов также хотел бы обсудить на 1:1, не совсем понял.

2024-01-11 07:09 UTC, merged